In [ ]:
import pandas as pd

In [ ]:
dados = {
    "dia": list(range(1, 16)),
    "faturamento": [3000, 3200, 3100, 2900, 3050,
                    2950, 3100, 3000, 3050, 3100,
                    2900, 2950, 3000, 2900, 50000]  # último dia com valor muito alto
}

df_fat = pd.DataFrame(dados)
df_fat

    dia  faturamento
0     1         3000
1     2         3200
2     3         3100
3     4         2900
4     5         3050
5     6         2950
6     7         3100
7     8         3000
8     9         3050
9    10         3100
10   11         2900
11   12         2950
12   13         3000
13   14         2900
14   15        50000

In [ ]:
df_fat["faturamento"].describe()

count       15.000000
mean      6146.666667
std      12131.974675
min       2900.000000
25%       2950.000000
50%       3000.000000
75%       3100.000000
max      50000.000000
Name: faturamento, dtype: float64

In [ ]:
f= df_fat["faturamento"]
q1 = f.quantile(0.25)
q3= f.quantile(0.75)
iqr= q3-q1

limite_inferior = q1-1.5*iqr
limite_superior = q3+1.5*iqr

In [ ]:
outliers= df_fat[(df_fat["faturamento"] < limite_inferior) | (df_fat["faturamento"] > limite_superior)]
outliers

    dia  faturamento
14   15        50000

In [ ]:
df_sem_outliers = df_fat[(df_fat["faturamento"] >= limite_inferior) & (df_fat["faturamento"] <= limite_superior)]
df_sem_outliers

    dia  faturamento
0     1         3000
1     2         3200
2     3         3100
3     4         2900
4     5         3050
5     6         2950
6     7         3100
7     8         3000
8     9         3050
9    10         3100
10   11         2900
11   12         2950
12   13         3000
13   14         2900

In [ ]:
df_clipado = df_fat.copy()
df_clipado["faturamento_limpo"] = df_clipado["faturamento"].clip(upper=limite_superior)

In [ ]:
df_fat["faturamento"].mean(), df_clipado["faturamento_limpo"].mean()

(np.float64(6146.666666666667), np.float64(3035.0))

In [ ]:
dados_pag = {
    "id_venda": [1, 2, 3, 4, 5, 6],
    "forma_pagamento": ["Crédito", "Débito", "Crédito", "Pix", "Dinheiro", "Crédito"],
    "valor": [100, 50, 200, 80, 40, 150]
}

df_pag = pd.DataFrame(dados_pag)
df_pag

   id_venda forma_pagamento  valor
0         1         Crédito    100
1         2          Débito     50
2         3         Crédito    200
3         4             Pix     80
4         5        Dinheiro     40
5         6         Crédito    150

In [ ]:
df_pag["forma_pagamento"] = df_pag["forma_pagamento"].astype("category")
df_pag.dtypes

id_venda              int64
forma_pagamento    category
valor                 int64
dtype: object

In [ ]:
df_pag["forma_pagamento"].cat.categories
df_pag["forma_pagamento"].cat.codes

0    0
1    2
2    0
3    3
4    1
5    0
dtype: int8

In [ ]:
df_pag["forma_pagamento"]= df_pag["forma_pagamento"].str.lower()
df_pag["forma_pagamento"]

0     crédito
1      débito
2     crédito
3         pix
4    dinheiro
5     crédito
Name: forma_pagamento, dtype: object

In [ ]:
df_pag["faturamento"] = df_pag["forma_pagamento"].astype("category")
df_pag["faturamento"].cat.categories

Index(['crédito', 'dinheiro', 'débito', 'pix'], dtype='object')

In [ ]:
##criando outro df para trabalhar com datas

datas= pd.date_range(start="2024-10-01", periods=10, freq="D")
dados = {
    "data": datas,
    "loja": ["Centro", "Centro", "Shopping", "Shopping", "Centro",
"Centro", "Shopping", "Centro", "Shopping", "Centro"],
    "faturamento": [3000, 3200, 5000, 4500, 2800, 2900, 5200, 3100, 4800, 3500]
}

df_vendas = pd.DataFrame(dados)
df_vendas

        data      loja  faturamento
0 2024-10-01    Centro         3000
1 2024-10-02    Centro         3200
2 2024-10-03  Shopping         5000
3 2024-10-04  Shopping         4500
4 2024-10-05    Centro         2800
5 2024-10-06    Centro         2900
6 2024-10-07  Shopping         5200
7 2024-10-08    Centro         3100
8 2024-10-09  Shopping         4800
9 2024-10-10    Centro         3500

In [ ]:
df_vendas["ano"]= df_vendas["data"].dt.year
df_vendas["mes"]= df_vendas["data"].dt.month
df_vendas["dia"] = df_vendas["data"].dt.day
df_vendas

        data      loja  faturamento   ano  mes  dia
0 2024-10-01    Centro         3000  2024   10    1
1 2024-10-02    Centro         3200  2024   10    2
2 2024-10-03  Shopping         5000  2024   10    3
3 2024-10-04  Shopping         4500  2024   10    4
4 2024-10-05    Centro         2800  2024   10    5
5 2024-10-06    Centro         2900  2024   10    6
6 2024-10-07  Shopping         5200  2024   10    7
7 2024-10-08    Centro         3100  2024   10    8
8 2024-10-09  Shopping         4800  2024   10    9
9 2024-10-10    Centro         3500  2024   10   10

In [ ]:
#exercicios aula8

In [ ]:
import pandas as pd

In [ ]:
dados_ex={
    "id_venda": list(range(1, 16)),
    "valor": [300, 450, 500, 600, 700,
              800, 1200, 1500, 1600, 1800,
              2000, 2200, 2500, 50000, 80000]

}

df_ex= pd.DataFrame(dados_ex)
df_ex
#

    id_venda  valor
0          1    300
1          2    450
2          3    500
3          4    600
4          5    700
5          6    800
6          7   1200
7          8   1500
8          9   1600
9         10   1800
10        11   2000
11        12   2200
12        13   2500
13        14  50000
14        15  80000

In [ ]:
df_ex["valor"].describe()

count       15.000000
mean      9743.333333
std      23149.551574
min        300.000000
25%        650.000000
50%       1500.000000
75%       2100.000000
max      80000.000000
Name: valor, dtype: float64

In [ ]:
q1= df_ex["valor"].quantile(0.25)
q3= df_ex["valor"].quantile(0.75)
iqr= q3-q1
limite_inferior = q1-1.5*iqr
limite_superior = q3+1.5*iqr

In [ ]:
outliers_ex=df_ex[(df_ex["valor"] < limite_inferior) | (df_ex["valor"] > limite_superior)]
print(outliers_ex)

    id_venda  valor
13        14  50000
14        15  80000

In [ ]:
df_ex_sem_outliers= df_ex[(df_ex["valor"] >= limite_inferior) & (df_ex["valor"] <= limite_superior)]

In [ ]:
df_ex_sem_outliers["valor"].describe()

count      13.000000
mean     1242.307692
std       738.761958
min       300.000000
25%       600.000000
50%      1200.000000
75%      1800.000000
max      2500.000000
Name: valor, dtype: float64

In [ ]:
#Em texto, responda:

    #Quantos outliers foram encontrados?
    #Resposta= Dois!
    #A média do faturamento mudou muito ao remover os outliers?
    #Resposta= Sim, a média mudou de 9743.33 para 1242.31 após a remoção dos outliers. A média utilizando o dataframe com os outliers é mais de 7 vezes maior do que a média usando o df sem outliers

In [ ]:
import numpy as np
datas= pd.date_range(start= "2026-01-01", periods=30, freq="D")

In [ ]:
dados = {
    "data": datas,
    "loja": ["Centro" if i % 2 == 0 else "Shopping" for i in range(30)],
    "faturamento_diario": np.random.randint(2000, 8000, size=30)
}

df_vendas = pd.DataFrame(dados)

In [ ]:
df_vendas["loja"] = df_vendas["loja"].astype("category")

In [ ]:
df_vendas["ano"]= df_vendas["data"].dt.year
df_vendas["mes"]= df_vendas["data"].dt.month
df_vendas["dia da semana num"] = df_vendas["data"].dt.weekday

In [ ]:
mapeamento_dias = {
    0: "Segunda", 1: "Terça", 2: "Quarta", 3: "Quinta",
    4: "Sexta",5: "Sábado", 6: "Domingo"
}

In [ ]:
#mapear os dias da seman com seus respectivos nomes